package org.freeplane.features.gtd.actions

const val GTD_IS_ACTIVE_PROP = "GTD_IS_ACTIVE_PROP"
const val GTD_IS_INSTALLED_PROP = "GTD_IS_INSTALLED_PROP"

const val GTD_IS_MODULE_EXIST_PROP = "GTD_IS_MODULE_EXIST_PROP"

const val GTD_IS_GLOB_MAP_SELECTED_PROP = "GTD_IS_GLOB_MAP_SELECTED_PROP"

const val GTD_SELECTED_INTENT_EXISTS_PROP = "GTD_SELECTED_INTENT_EXISTS_PROP"